@echo off
echo Killing all Node.js processes...
taskkill /f /im node.exe 2>nul
echo Waiting for ports to clear...
timeout /t 3 /nobreak >nul
echo Starting server...
cd /d "c:\Users\Account\Desktop\CRM-ogcs\crm-backend"
npm run dev
